### 3. Sơ đồ thực thể dữ liệu (ERD)

![Cấu trúc Database CareFirst](./images/CareFirstClinic_erd-diagram.png)

> **Mẹo:** Bạn có thể xem mã nguồn cấu trúc database chi tiết tại link : https://dbdocs.io/viet01386/CareFirstClinic_erd-diagram Pass:123456